# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=200)),
                ('open', models.CharField(max_length=200)),
                ('high', models.CharField(max_length=200)),
                ('low', models.CharField(max_length=200)),
                ('close', models.CharField(max_length=200)),
                ('volume', models.CharField(max_length=200)),
                ('adj', models.CharField(max_length=200)),
                ('stock', models.CharField(max_length=200)),
            ],
        ),
    ]
