# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20160715_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(max_length=200),
        ),
    ]
